config/routes.rb
Rails.application.routes.draw do
  root to: "dashboards#index"

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    get '/dashboard/:id', to: 'dashboard#show', as: 'order'
    post '/dashboard', to: 'dashboard#edit_status'
    resources :products
  end

  resources :users
  resources :orders
  resources :brands
  resources :products
  resources :categories
  resources :shopping_carts

  get "/cart", to: "shopping_carts#index"
  put "/cart", to: "shopping_carts#update"
  delete "/update_cart", to: "shopping_carts#destroy"
  post "/order", to: "orders#create"

  get "/dashboard", to: "users#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get '/:category_name', to: 'categories#show'
end

app/models/shopping_cart.rb
class ShoppingCart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def total_count
    contents.values.sum
  end

  def add_product(id)
    contents[id.to_s] = (contents[id.to_s] || 0) + 1
  end

  def count_of(id)
    contents[id.to_s].to_i
  end

  def show_products
    contents.reduce({}) do |final, (product_id, count)|
      final[Product.find(product_id.to_i)] = count
      final
    end
  end

  def total_price
    contents.reduce(0) do |price, (product_id, count)|
      price += (Product.find(product_id.to_i).price * count)
      price
    end
  end

  def remove_product(id)
    contents.delete(id)
  end

  def change_quantity(product_id, quantity)
    @contents[product_id.to_s] += quantity.to_i
    remove_product(product_id) if @contents[product_id.to_s] <= 0
  end


end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    product = Product.find(params[:product_id])
    @shopping_cart.add_product(product.id)
    session[:shopping_cart] = @shopping_cart.contents

    flash[:notice] = "#{pluralize(@shopping_cart.count_of(product.id), product.name)} in Cart"
    redirect_to products_path
  end

  def index
    @products = Product.all
  end

  def destroy
    product = Product.find(params[:product_id])
    @shopping_cart.remove_product(params[:product_id])
    flash[:notice] = %Q[Successfully removed <a href="/products/#{product.id}"> #{product.name}</a> from your cart].html_safe
    session[:shopping_cart] = @shopping_cart.contents
    redirect_to cart_path
  end

  def update
    @shopping_cart.change_quantity(params[:product_id], params[:quantity_change])
    session[:shopping_cart] = @shopping_cart.contents
    redirect_to cart_path
  end
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/index.html.erb
<div class="well">
  <table class="table table-striped" id="cart-contents">
    <% if current_user ==nil %>
    <% end %>

    <% @shopping_cart.show_products.each do |product, count| %>
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Remove</th>
      </tr>
      <td> <span class="thumbnail-custom"><%= image_tag(product.image_path)%></span></td>
      <td> Name: <%= product.name %></td>
      <td> Description: <%= product.description %></td>
      <td> Price: <%= product.price %></td>
      <td>
        <div class="input-group center-buttons">
          <span class="input-group-btn">
             <%= link_to cart_path(product_id: product.id, quantity_change: -1), method: "put" do %><button type="button" class="btn btn-danger btn-number"  data-type="minus" data-field="quant[2]">
               <div style="position: absolute; left: -10000px;">-</div><span class="glyphicon glyphicon-minus"></span>
             </button><% end %>
         </span>
         <input type="text" name="quant[2]" class="form-control input-number" value=<%= count %> min="1" max="100">
        <span class="input-group-btn">
              <%= link_to cart_path(product_id: product.id, quantity_change: 1), method: "put" do %><button type="button" class="btn btn-success btn-number" data-type="plus" data-field="quant[2]">
              <span class="glyphicon">+</span>
            </button><% end %>
        </span>
        </div>
      </td>
      <td>
        <%= button_to "Remove Product", update_cart_path(product_id: product.id), method: :delete, class: "btn btn-success" %>
      <% end %>
      </td>
  </table>

  Cart Total: <%= @shopping_cart.total_price %>
  <% if current_user %>
    <%= link_to "Checkout", orders_path, method: :post, class: 'current_user_accessible' %>
   <% else %>
     <%= link_to "Please login or create an account to checkout.", login_path %>
   <% end %>
</div>

app/views/shopping_carts/show.html.erb
<% @shopping_cart.show_products.each do |product, count| %>
  <span class="thumbnail-custom"><%= image_tag(product.image_path)%></span>
  Name: <%= product.name %>
  Description: <%= product.description %>
  Price: <%= product.price %>
  Item Total: <%= count %>
<% end %>
</br>
Cart Total: <%= @shopping_cart.total_price %>