config/routes.rb
Rails.application.routes.draw do
  root to: "dashboards#index"

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    get '/dashboard/:id', to: 'dashboard#show', as: 'order'
    post '/dashboard', to: 'dashboard#edit_status'
    resources :products
  end

  resources :users
  resources :orders
  resources :brands
  resources :products
  resources :categories
  resources :shopping_carts

  get "/cart", to: "shopping_carts#index"
  put "/cart", to: "shopping_carts#update"
  delete "/update_cart", to: "shopping_carts#destroy"
  post "/order", to: "orders#create"

  get "/dashboard", to: "users#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get '/:category_name', to: 'categories#show'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController <Admin::BaseController
 
  def index
    if params.include?("status")
      @order = Order.where(status: params[:status])
      render :status
    else
      @orders = Order.all 
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def edit_status
    @order = Order.find(params[:order_id])
      if @order.status == 'ordered'
      @order.update_attribute :status, 1

      redirect_back(fallback_location: admin_dashboard_path)
    elsif @order.status == 'paid'
      @order.update_attribute :status, 2

      redirect_back(fallback_location: admin_dashboard_path)
    end
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @products = Product.order("created_at ASC").limit(4)
  end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/admin/dashboard/_ordered.html.erb
<h1>All orders with ordered status</h1>

<% @ordered_products = Order.where(status: 0) %>

<% @ordered_products.each do |ordered_product| %>
<%= ordered_product.id %>
<%= ordered_product.price %>
<% end %>

app/views/admin/dashboard/index.html.erb
<div class="container">
  <%= link_to "Products", admin_products_path, class: "admin-delete" %>
  <div class="row">
    <div class="page-header text-center"><h1>Admin Dashboard</h1></div>
    <div class="col-md-6 text-center">
      <h3>All Orders</h3>
      <ul class="list-group"><% @orders.each do |order| %>
        <li class="list-group-item">View order: <%= link_to "#{order.id}", admin_order_path(order) %><br>
          Order Created: <%= order.created_at.strftime("%b. %d, %Y") %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="col-md-6 text-center">
      <h3>Orders by Status</h3>
      <ul class="list-group">
        <% ordered_amount = Order.where(status: 0).count %>
        <% paid_amount = Order.where(status: 1).count %>
        <% cancelled_amount = Order.where(status: 2).count %>
        <% completed_amount = Order.where(status: 3).count %>

        <li class="list-group-item">Ordered: <%= ordered_amount %><br></li>
        <li class="list-group-item">Paid: <%= paid_amount  %><br></li>
        <li class="list-group-item">Cancelled: <%= cancelled_amount %><br></li>
        <li class="list-group-item">Completed: <%= completed_amount %><br></li>
      </ul>
    </div>
    <div class="col-md-6 text-center">
      <h3>Filter by Status</h3>
      <ul class="list-group">
        <li class="list-group-item"><%= link_to "Ordered", {controller: 'dashboard', action: 'index', :status => 0} %></li>
        <li class="list-group-item"><%= link_to "Paid", {controller: 'dashboard', action: 'index', :status => 1} %>
</li>
        <li class="list-group-item"><%= link_to "Cancelled", {controller: 'dashboard', action: 'index', :status => 2} %></li>
        <li class="list-group-item"><%= link_to "Completed", {controller: 'dashboard', action: 'index', :status => 3} %></li>
      </ul>
    </div>
  </div>
</div>

app/views/admin/dashboard/show.html.erb
<%= @order.user.username %>
<%= @order.id %>
<%= @order.created_at %>
<%= @order.user.full_name %>
<%= @order.user.address %>
<%= @order.status %>
<% @order.products.uniq.each_with_index do |product, index| %>
  <%= link_to product.name, product_path(product) %>
  <%= product.price %>
  <%= @order.quantity[product.id] %>
  <%= @order.line_total[index] %>
<% end %>

Total Price: $<%= @order.total_price %>

app/views/admin/dashboard/status.html.erb
<%= link_to "Paid", {controller: 'dashboard', action: 'index', :status => 1} %>

<%= link_to "Cancelled", {controller: 'dashboard', action: 'index', :status => 2} %>

<%= link_to "Completed", {controller: 'dashboard', action: 'index', :status => 3} %>
<br>

<% @order.each do |order| %>
  <%= order.id %>
  <%= order.user.username %>

  <% if order.status == "ordered" %>
    <%= button_to "Mark Paid", admin_dashboard_path(order_id: order.id) %>
<% end %>


  <% if order.status == "paid" || order.status == 'ordered' %>
    <%= button_to "Cancel", admin_dashboard_path(order_id: order.id) %>
<% end %>


  <% if order.status == "paid" %>
    <%= button_to "Mark Completed", admin_dashboard_path(order_id: order.id) %>
<% end %>

<% end %>
<br>
<%= link_to "Back to Dashboard", admin_dashboard_path %>