config/routes.rb
Rails.application.routes.draw do
  root to: "dashboards#index"

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    get '/dashboard/:id', to: 'dashboard#show', as: 'order'
    post '/dashboard', to: 'dashboard#edit_status'
    resources :products
  end

  resources :users
  resources :orders
  resources :brands
  resources :products
  resources :categories
  resources :shopping_carts

  get "/cart", to: "shopping_carts#index"
  put "/cart", to: "shopping_carts#update"
  delete "/update_cart", to: "shopping_carts#destroy"
  post "/order", to: "orders#create"

  get "/dashboard", to: "users#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get '/:category_name', to: 'categories#show'
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :order_products
  has_many :orders, through: :order_products
  belongs_to :brand
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  
  enum role: %w(active retired)

  def self.search(query)
    if query
      where('name LIKE ?', "%#{query}%")
    else
      Product.all
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  def new
    @product = Product.new
    @categories = Category.all
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      flash[:notice] = "Invalid Credentials"
      redirect_to edit_admin_product_path(@product, name: @product.name)
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_dashboard_path
    else
      redirect_to new_admin_product_path
    end
  end

  def index
    @products = Product.all
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :brand_id, category_ids: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    if @product.save
      flash[:success] = "Product Updated!"
      redirect_to product_path(@product)
    else
      flash[:notice] = "Invalid Credentials"
      render :edit
    end
  end

  def index
    @products = Product.all
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/views/products/edit.html.erb
<%= form_for(@product) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label :brand %>
  <%= f.collection_select(:brand_id, Brand.all, :id, :name, {class: "form-control"}) %>

  <%= f.label :categories %>
  <%= collection_check_boxes(:product, :category_ids, Category.all, :id, :name) %>
  <%= f.submit%>
 <% end %>

app/views/products/index.html.erb
<div class="container">
    <div class="well well-sm">
        <strong>All Products</strong>
        <div class="btn-group">
            <a href="#" id="list" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-th-list">
            </span>List</a> <a href="#" id="grid" class="btn btn-default btn-sm"><span
                class="glyphicon glyphicon-th"></span>Grid</a>
        </div>
    </div>
    <div id="products" class="row list-group">
      <% @products.each do |product| %>
        <div class="item  col-xs-4 col-lg-4">
            <div class="thumbnail custom-height">
                <img class="group list-group-image" src=<%= "#{product.image_path}" %> alt="" />
                <div class="caption">
                    <h4 class="group inner list-group-item-heading">
                        <%= "#{product.name}" %></h4>
                    <p class="group inner list-group-item-text">
                        <%= "#{product.description}" %></p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p class="lead">
                                $<%= "#{product.price}" %></p>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div><%= button_to "Add Product", shopping_carts_path(product_id: product.id), class: "btn btn-success center-block" %></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>
  </div>

app/views/products/new.html.erb
<%= form_for(:product, url: products_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label :brand %>
  <%= f.collection_select(:brand_id, Brand.all, :id, :name, {class: "form-control"}) %>

  <%= f.label :categories %>
  <%= collection_check_boxes(:product, :category_ids, Category.all, :id, :name) %>
  <%= f.submit  %>
 <% end %>

app/views/products/show.html.erb
<table class="table table-striped" id="cart-contents">
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
    </tr>
    <td> <span class="thumbnail-custom"><%= image_tag(@product.image_path)%></span></td>
    <td> <%= @product.name%></td>
    <td> <%= @product.description %></td>
    <td> <%= @product.price %></td>
</table>

<% if @product.active?  %>
<%= button_to "Add Product", shopping_carts_path(product_id: @product.id), class: "btn btn-success"%>
<% elsif @product.retired? %>
<%= button_to "Item Retired", products_path, class: "btn btn-success"%>
<% end %>
<% if current_admin? %>
<%= link_to "Delete", product_path(@product), method: :delete %>
<% end %>