config/routes.rb
Rails.application.routes.draw do
  root to: "dashboards#index"

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    get '/dashboard/:id', to: 'dashboard#show', as: 'order'
    post '/dashboard', to: 'dashboard#edit_status'
    resources :products
  end

  resources :users
  resources :orders
  resources :brands
  resources :products
  resources :categories
  resources :shopping_carts

  get "/cart", to: "shopping_carts#index"
  put "/cart", to: "shopping_carts#update"
  delete "/update_cart", to: "shopping_carts#destroy"
  post "/order", to: "orders#create"

  get "/dashboard", to: "users#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get '/:category_name', to: 'categories#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GearUpp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <div id="flipkart-navbar">
        <div class="container navbar-static">
          <div class="col-md-1"><%= image_tag('gearupp_logo', class: "logo-bar") %></div>
            <div class="row row1 col-md-8">
                <ul class="largenav pull-right">
                <li class="upper-links"><a class="links"><%= link_to "Home", root_path, class: "links" %></a></li>
                <li class="upper-links">
                <% if current_user %>
                  <%= link_to "Logged in as #{ current_user.username}", user_path(current_user), class: "links" %>  &nbsp &nbsp <strong>
                    <%= link_to "Logout?", logout_path, method: :delete, class: "links" %></strong>
                 <% else %>
                   <%= link_to "Login", login_path, class:"links login-navbar-unique" %>
                 <% end %>
                </li>
                <li class="upper-links">
                    <a class="links">
                      <%= link_to "Products", products_path, class: "links" %>
                    </a>
                </li>
                <li class="upper-links dropdown"><a class="links">Categories</a>
                    <ul class="dropdown-menu"><% @categories.each do |category| %>
                        <li class="profile-li"><a class="profile-links"><%= link_to category.name, "/#{category.name}" %></a></li>
                        <% end %>
                    </ul>
                </li>
                <li class="upper-links dropdown"><a class="links" href="">Brands</a>
                    <ul class="dropdown-menu">
                        <li class="profile-li"><a class="profile-links" href="">Link</a></li>
                        <li class="profile-li"><a class="profile-links" href="">Link</a></li>
                        <li class="profile-li"><a class="profile-links" href="">Link</a></li>
                        <li class="profile-li"><a class="profile-links" href="">Link</a></li>
                        <li class="profile-li"><a class="profile-links" href="">Link</a></li>
                        <li class="profile-li"><a class="profile-links" href="">Link</a></li>
                        <li class="profile-li"><a class="profile-links" href="">Link</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="row row2">
            <div class="col-sm-2">
                <h2 style="margin:0px;"><span class="smallnav menu" onclick="openNav()">☰ GearUpp</span></h2>
                <!-- <h1 style="margin:0px;"><span class="largenav"> <%= link_to image_tag("gearupp_logo.png", alt: "logo"), '/', class: 'navbar-brand' %></span></h1> -->
            </div>
            <div class="flipkart-navbar-search smallsearch col-sm-8 col-xs-11">
              <div class="row">
                  <form class="flipkart-navbar-input col-xs-11" role="search" method="get" id="searchform" action='/products'>
                    <div class="form-group">
                      <input name="query" id="query" type="text" class="search-query form-control" autocomplete="on" placeholder="Search products">
                    </div>
                  <button class="flipkart-navbar-button col-xs-1 search-button">
                      <svg width="15px" height="15px">
                          <path d="M11.618 9.897l4.224 4.212c.092.09.1.23.02.312l-1.464 1.46c-.08.08-.222.072-.314-.02L9.868 11.66M6.486 10.9c-2.42 0-4.38-1.955-4.38-4.367 0-2.413 1.96-4.37 4.38-4.37s4.38 1.957 4.38 4.37c0 2.412-1.96 4.368-4.38 4.368m0-10.834C2.904.066 0 2.96 0 6.533 0 10.105 2.904 13 6.486 13s6.487-2.895 6.487-6.467c0-3.572-2.905-6.467-6.487-6.467 "></path>
                      </svg>
                  </button>
              </div>
            </div>
            <div class="cart largenav col-sm-2">
              <a class="cart-button"<%= link_to cart_path do %>
                    <svg class="cart-svg" width="16 " height="16 " viewBox="0 0 16 16 ">
                        <path d="M15.32 2.405H4.887C3 2.405 2.46.805 2.46.805L2.257.21C2.208.085 2.083 0 1.946 0H.336C.1 0-.064.24.024.46l.644 1.945L3.11 9.767c.047.137.175.23.32.23h8.418l-.493 1.958H3.768l.002.003c-.017 0-.033-.003-.05-.003-1.06 0-1.92.86-1.92 1.92s.86 1.92 1.92 1.92c.99 0 1.805-.75 1.91-1.712l5.55.076c.12.922.91 1.636 1.867 1.636 1.04 0 1.885-.844 1.885-1.885 0-.866-.584-1.593-1.38-1.814l2.423-8.832c.12-.433-.206-.86-.655-.86 " fill="#fff "></path>
                    <%= link_to "Your Cart", cart_path, class: "btn"%></svg>
                    <span class="item-number"><%= @shopping_cart.total_count %></span>
                </a>
          <% end %></div>
        </div>
    </div>
</div>
<div id="mySidenav" class="sidenav">
    <div class="container" style="background-color: #2874f0; padding-top: 10px;">
        <span class="sidenav-heading">Home</span>
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    </div>
    <a href="">Link</a>
    <a href="">Link</a>
    <a href="">Link</a>
    <a href="">Link</a>
</div>

    <% flash.each do |type, message| %>
      <%= content_tag :div, sanitize(message), class: type %>
    <% end %>

    <%= yield %>


    <div class="container">

    <hr class="featurette-divider">
          <footer class = "footer">
            <p class="pull-right"><a href="#">top</a></p>
            <p class="pull-left">
        	<small>
    		<a href="https://github.com/Mcents/little_shop" target="_blank">About Us</a> <bR>
    		<a href="#">Support</a><bR>

    		<a  href="https://www.google.com/maps/place/Turing+School+of+Software+%26+Design/@39.7508006,-104.9987834,17z/data=!3m1!4b1!4m5!3m4!1s0x876c78c4f77d2b15:0x3ff4c7d558d0edd1!8m2!3d39.7508006!4d-104.9965947" target="_blank">Location</a>


    		</small>
    		</p>

    	<center><p> Copyright 2017<bR><small>by GearUpp</small> </p></center>

          </footer>
         </div>

  </body>


</html>